spring.application.name=assesment
# ================================
# H2 DATABASE CONFIGURATION
# ================================
spring.datasource.url=jdbc:mysql://host.docker.internal:3306/project_microservice?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Qwe.123*

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# Show h2 logs
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.open-in-view=false

# ================================
# SERVER
# ================================
server.port=8080
jwt.secret=SgX4h6uVvOa20Nm2QpD8L4ZyJh9YsYz3T8U9rYtC5nw=

management.endpoints.web.exposure.include=health,info,metrics,prometheus

# Info
management.info.env.enabled=true
management.info.app.name=AssessmentService
management.info.app.version=1.0.0

# Health
management.endpoint.health.show-details=always

# Metrics
management.metrics.enable.all=true
management.metrics.tags.application=assessment